const catalogEl=document.getElementById('catalog');
const cartBtn=document.getElementById('cart-button');
const cartCountEl=document.getElementById('cart-count');
const modalBack=document.getElementById('modal-back');
const modalContent=document.getElementById('modal-content');
const themeToggle=document.getElementById('theme-toggle');
const langSelect=document.getElementById('lang-select');
let cart=[];
const catalog=[
{id:1,name:"Черная куртка",price:12000,sizes:[{size:"S",chest:50,length:65},{size:"M",chest:52,length:67},{size:"L",chest:55,length:70}]},
{id:2,name:"Белая рубашка",price:4500,sizes:[{size:"S",chest:48,length:62},{size:"M",chest:50,length:64},{size:"L",chest:53,length:66}]},
{id:3,name:"Джинсы скинни",price:7800,sizes:[{size:"S",waist:70,length:95},{size:"M",waist:74,length:97},{size:"L",waist:78,length:100}]}];
function renderCatalog(){catalogEl.innerHTML="";catalog.forEach(item=>{const card=document.createElement('div');card.className='card';const img=document.createElement('div');img.className='imgplace';img.textContent=item.name;const title=document.createElement('div');title.textContent=item.name;const price=document.createElement('div');price.textContent=item.price+' ₽';const actions=document.createElement('div');actions.className='actions';const sizeBtn=document.createElement('button');sizeBtn.className='btn-ghost';sizeBtn.textContent='Выбрать размер';sizeBtn.onclick=()=>openModal(item,true);const buyBtn=document.createElement('button');buyBtn.className='btn-primary';buyBtn.textContent='Купить';buyBtn.onclick=()=>openModal(item,false);const addBtn=document.createElement('button');addBtn.className='btn-ghost';addBtn.textContent='В корзину';addBtn.onclick=()=>addToCart(item);actions.appendChild(sizeBtn);actions.appendChild(buyBtn);actions.appendChild(addBtn);card.appendChild(img);card.appendChild(title);card.appendChild(price);card.appendChild(actions);catalogEl.appendChild(card);});}
function addToCart(item,qty=1,size='M'){cart.push({...item,count:qty,size:size});updateCart();}
function updateCart(){cartCountEl.textContent=cart.length;}
function openModal(item,showSizeOnly=false){modalContent.innerHTML=`<h2>${item.name}</h2>`;if(item.sizes&&item.sizes.length>0){modalContent.innerHTML+=`<div>Выберите размер</div>`;const sizeList=document.createElement('div');sizeList.className='size-list';item.sizes.forEach(sz=>{const div=document.createElement('div');div.className='size-item';div.textContent=sz.size+' ('+(sz.chest?('Грудь:'+sz.chest+'см, '):'')+(sz.waist?('Талия:'+sz.waist+'см, '):'')+(sz.length?('Длина:'+sz.length+'см'):'')+')';div.onclick=()=>{document.querySelectorAll('.size-item').forEach(si=>si.classList.remove('active'));div.classList.add('active');};sizeList.appendChild(div);});modalContent.appendChild(sizeList);}if(!showSizeOnly){modalContent.innerHTML+=`<div><label>Количество</label><input type="number" id="modal-qty" value="1" min="1"/></div><div><button class="btn-primary" id="modal-addcart">Добавить в корзину и оформить</button></div>`;document.getElementById('modal-addcart').onclick=()=>{const qty=parseInt(document.getElementById('modal-qty').value)||1;const size=document.querySelector('.size-item.active')?.textContent.split(' ')[0]||'M';addToCart(item,qty,size);modalBack.style.display='none';openCart();}}modalBack.style.display='flex';}
modalBack.onclick=e=>{if(e.target===modalBack)modalBack.style.display='none';}
themeToggle.onclick=()=>{document.body.dataset.theme=document.body.dataset.theme==='dark'?'light':'dark';}
langSelect.onchange=()=>{const lang=langSelect.value;document.querySelector('.hero h1').textContent=lang==='ru'?'Добро пожаловать':'Welcome';document.querySelector('.hero p').textContent=lang==='ru'?'Предзаказ дизайнерских вещей':'Preorder designer items';}
function openCart(){modalContent.innerHTML=`<h2>Корзина</h2>`;if(cart.length===0){modalContent.innerHTML+='<p>Корзина пуста</p>';return;}cart.forEach((item,i)=>{modalContent.innerHTML+=`<div>${item.name} x${item.count} ${item.size} <button onclick="cart.splice(${i},1);updateCart();openCart();">Удалить</button></div>`;});modalContent.innerHTML+=`<div><button class="btn-primary" onclick="checkout()">Оформить заказ</button></div>`;}
function checkout(){let total=cart.reduce((sum,it)=>sum+it.price*it.count,0);let address=prompt("Введите адрес доставки","");let region=prompt("Введите регион","");let currency=prompt("Выберите валюту (₽,$,€)","₽");alert('Заказ оформлен! Сумма: '+total+' '+currency+'\nАдрес: '+address+'\nРегион: '+region);cart=[];updateCart();modalBack.style.display='none';}
cartBtn.onclick=openCart;
renderCatalog();